# 使用 § 颜色代码, 不会可以去查
# {index} 代表现在所处位置
msg:
  - "你现在的位置是{index}"
  - "§e§l如果超过3分钟没有<返回服务器列表><重新连接服务器>, 你会被重新放到队列末尾"
  - "§e§l如果你在序号为1, 服务器有空位时<超过10s没连接>, 则会先放行其他玩家"
  - "可使用自动重连插件AutoReconnect-Reforged"

# 超过该时间未重连, 重新放到队尾
queue_time_out: 180
# 服务器有空位时, 超过该时间未连接, 放行后面的玩家
wait_time_out: 10
# 两个玩家进入的时间间隔，单位ms
interval_time: 200
# 服务器最大玩家数，-1代表使用默认上限(使用默认上限 会导致排到第一位发现服务器已满)
max_players: -1