# 使用 § 颜色代码, 不会可以去查
# {index} 代表现在所处位置
msg:
- "你现在的位置是{index}"
- "§e§l如果超过1分钟没有重新连接服务器, 你会被重新放到队列末尾"
- "§e§l如果你在队列的前端, 服务器有空位时超过10s没连接, 则会先放行其他玩家"

# 超过该时间未重连, 重新放到队尾
queue_time_out: 60
# 服务器有空位时, 超过该时间未连接, 放行后面的玩家
wait_time_out: 10
# 两个玩家进入的时间间隔，单位ms(可能与玩家放行后 服务器已满有关)
interval_time: 200